{{- if or .Values.serviceAccount.create .Values.vault.injector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-info-service.serviceAccountName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
